= Iev

image:https://img.shields.io/gem/v/iev.svg["Gem Version", link="https://rubygems.org/gems/iev"]
image:https://travis-ci.com/metanorma/iev.svg["Build Status", link="https://travis-ci.com/metanorma/iev"]
image:https://ci.appveyor.com/api/projects/status/qifxbnyscgwgca0y?svg=true["Appveyor Build Status", link="https://ci.appveyor.com/project/metanorma/iev"]
image:https://codeclimate.com/github/metanorma/iev/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/iev"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/iev.svg["Pull Requests", link="https://github.com/metanorma/iev/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/iev/latest.svg["Commits since latest",link="https://github.com/metanorma/iev/releases"]

Fetch and encode IEV term from Electropedia.

== Installation

Add this line to your application's Gemfile:

[source, ruby]
----
gem 'iev'
----

And then execute:

    $ bundle

Or install it yourself as:

    $ gem install iev

== Usage

[source, ruby]
----
# Get term

Iev.get("103-01-02", "en")
=> "functional"

# If code not found
Iev.get("111-11-11", "en")
=> ""

# If language not found
Iev.get("103-01-02", "eee")
=> nil
----

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to [rubygems.org](https://rubygems.org).

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/iev.

== License

The gem is available as open source under the terms of the [MIT License](https://opensource.org/licenses/MIT).
